### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath': Could not download xposedcompat.aar (com.swift.sandhook:xposedcompat:4.0.0)

### ISSUE THREAD

**Issue by dengjiaming** [ganyao114/SandHook#18]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not download xposedcompat.aar (com.swift.sandhook:xposedcompat:4.0.0)

**Comment by ganyao114** [comment]
maven {
10
            url "https://dl.bintray.com/ganyao114/maven/"
11
        }
