### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath': Could not download xposedcompat.aar (com.swift.sandhook:xposedcompat:4.0.0)

### ISSUE THREAD

**Issue by dengjiaming** [ganyao114/SandHook#19]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        maven {
            url uri('./repo')
        }
        maven {
            url "https://dl.bintray.com/ganyao114/maven/"
        }
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        classpath 'com.flamingo.gradle.mess:mess:1.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

ext {
    compileSdkVersion = 28
    targetSdkVersion = 22
    minSdkVersion = 21 
    supportVersion = '28.0.0'
    junitVersion = '4.12'
    espressoVersion = '2.2.2'
}

allprojects {
    repositories {
        maven {
            url "https://dl.bintray.com/ganyao114/maven/"
        }
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
还是不行

**Comment by ganyao114** [comment]
那你应该检查一下你的网络了

**Comment by dengjiaming** [comment]
确实是网络问题
