### ISSUE TITLE
怎么对构造函数进行hook

### ISSUE THREAD

**Issue by Caij** [ganyao114/SandHook#32]
没有看到相关的文档或者demo

**Comment by fankes** [comment]
可以用xposed style

**Comment by ganyao114** [comment]
不输入函数名就默认是构造函数

**Comment by Caij** [comment]
还有一个问题就是hook系统hide api， 出现class找不到问题   有什么好的处理办法

**Comment by fankes** [comment]
class.forname

**Comment by ganyao114** [comment]
> 还有一个问题就是hook系统hide api， 出现class找不到问题 可以有什么好的处理办法吗
> @ganyao114

SandHook.passApiCheck();

**Comment by Caij** [comment]
使用 hooklib:4.0.0  Android Q 闪退。
但是使用github源码的demo正常。 4.0.0是最新的代码吗？
非常感谢

**Comment by ganyao114** [comment]
> 使用 hooklib:4.0.0 Android Q 闪退。
> 但是使用github源码的demo正常。 4.0.0是最新的代码吗？
> 非常感谢
> @ganyao114

4.0.2，另外 MIUI 的 Q 暂不支持

**Comment by Caij** [comment]
thanks
