### ISSUE TITLE
我只想说，跪求出个sandxposed

### ISSUE THREAD

**Issue by BoBppy** [ganyao114/SandHook#4]

**Comment by ganyao114** [comment]
有计划做一个，不过沙箱部分不会开源

**Comment by menglinxi** [comment]
沙箱部分,除了,virtualapp,还有其他么?

**Comment by supei328** [comment]
沙箱部分是基于VA进行优化的吗

**Comment by ganyao114** [comment]
> 沙箱部分,除了,virtualapp,还有其他么?

有我司自己的沙箱，目前还没做好，也不会开源

**Comment by ganyao114** [comment]
> 沙箱部分是基于VA进行优化的吗

有我司自己的沙箱，目前还没做好，也不会开源
