### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sfsunk** [ganyao114/SandHook#5]
hooklib 的build.gradle文件，    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }  去掉编译才通过。。。。

**Comment by ganyao114** [comment]
> hooklib 的build.gradle文件， externalNativeBuild {
> cmake {
> path "CMakeLists.txt"
> }
> } 去掉编译才通过。。。。

1. 看一下 NDK 是否正确配置
2. 高版本 NDK 已经不支持 GCC 了，建议使用 NDK16 及以下版本

**Comment by sfsunk** [comment]
谢谢回复：）！！问一下，是否支持andorid5.0, 5.1 的64 位cpu手机?

**Comment by ganyao114** [comment]
> 谢谢回复：）！！问一下，是否支持andorid5.0, 5.1 的64 位cpu手机?

已知三星 5.0 可能会有问题，魔改得太严重，其他应该没什么问题

**Comment by sfsunk** [comment]
：（ndk r16b 编译依然报错。能否把 'armeabi-v7a', 'arm64-v8a' 的so文件发我邮箱，我来测下5.X的支持情况。
