### ISSUE TITLE
DexMaker.generateClassLoader会卡出

### ISSUE THREAD

**Issue by zy990081568** [ganyao114/SandHook#8]
return (ClassLoader) Class.forName("dalvik.system.DexClassLoader")
                        .getConstructor(String.class, String.class, String.class, ClassLoader.class)
                        .newInstance(result.getPath(), dexCache.getAbsolutePath(), null,
                                preferredClassLoader)
这一行会卡住是什么原因呀 魅蓝5s flyme5

hook返回值为long类型的方法

**Comment by ganyao114** [comment]
卡住？去掉 MyApp.java 中的 SandHook.disableDex2oatInline 这一行试试

**Comment by ganyao114** [comment]
> return (ClassLoader) Class.forName("dalvik.system.DexClassLoader")
> .getConstructor(String.class, String.class, String.class, ClassLoader.class)
> .newInstance(result.getPath(), dexCache.getAbsolutePath(), null,
> preferredClassLoader)
> 这一行会卡住是什么原因呀 魅蓝5s flyme5
> 
> hook返回值为long类型的方法

去掉 MyApp.java 中的 SandHook.disableDex2oatInline 这一行试试

**Comment by zy990081568** [comment]
没有找到MyApp这个类, 但是我直接把SandHook里面的这个方法注释掉没有用
![image](https://user-images.githubusercontent.com/10340599/56268628-6738bf80-6124-11e9-8c48-99b420f20adb.png)
圈住的这个地方会卡出, 具体卡住的点是上面构建DexClassLoader实例的时候会卡住

**Comment by ganyao114** [comment]
> 没有找到MyApp这个类, 但是我直接把SandHook里面的这个方法注释掉没有用
> ![image](https://user-images.githubusercontent.com/10340599/56268628-6738bf80-6124-11e9-8c48-99b420f20adb.png)
> 圈住的这个地方会卡出, 具体卡住的点是上面构建DexClassLoader实例的时候会卡住

IOUniformer.cpp 中 613 行

`if (isSandHooker(argv)) {
            return -1;
        }` 

删掉试试

**Comment by zy990081568** [comment]
> > 没有找到MyApp这个类, 但是我直接把SandHook里面的这个方法注释掉没有用
> > ![image](https://user-images.githubusercontent.com/10340599/56268628-6738bf80-6124-11e9-8c48-99b420f20adb.png)
> > 圈住的这个地方会卡出, 具体卡住的点是上面构建DexClassLoader实例的时候会卡住
> 
> IOUniformer.cpp 中 613 行
> 
> `if (isSandHooker(argv)) { return -1; }`
> 
> 删掉试试

可以了, 更新了你昨天提交的代码就没这个问题了,  非常感谢

**Comment by ganyao114** [comment]
> > > 没有找到MyApp这个类, 但是我直接把SandHook里面的这个方法注释掉没有用
> > > ![image](https://user-images.githubusercontent.com/10340599/56268628-6738bf80-6124-11e9-8c48-99b420f20adb.png)
> > > 圈住的这个地方会卡出, 具体卡住的点是上面构建DexClassLoader实例的时候会卡住
> > 
> > 
> > IOUniformer.cpp 中 613 行
> > `if (isSandHooker(argv)) { return -1; }`
> > 删掉试试
> 
> 可以了, 更新了你昨天提交的代码就没这个问题了, 非常感谢

👌
